#few_shotで使用するサービス一覧
#使用サービス：bible-mapped, wishgenies, RADAAR, 2lingual-bing-search, aircellcall
few_shot_examples = [
    {   #1つ目
        "role": "user",
        "content": "Requirements: Mashup showing locations of 200 places mentioned in the Bible. Going for accuracy they try to pinpoint the locations of the ruins of ancient cities instead of using the locations of modern cities with ancient names.\n"
                "Answer:\n"
                "1. **Identify Core Features**:\n"
                "   - mapping: The mashup requires depicting the precise locations of historical biblical sites, which entails utilizing geolocation and mapping services to represent these places accurately.\n"
                "   - historical reference: The need to locate ancient city ruins ties into accessing historical references about biblical sites, ensuring that the mapped locations are historically accurate.\n\n"
                "2. **Identify Relevant API Categories**:\n"
                "   - mapping: Essential for visualizing and geolocating the ruins of ancient cities mentioned in the Bible.\n"
                "   - reference: Useful for obtaining detailed, historically accurate information about the biblical places to ensure correct representation on the map.\n\n"
                "3. **Match APIs from Relevant Categories**:\n"
                "   - **mapping APIs**:\n"
                "       - google-maps: Provides comprehensive mapping capabilities, including geolocation, which is essential for accurately depicting the locations of ancient ruins.\n"
                "       - google-geocoding: Offers geocoding and reverse geocoding services which can help transform location data into map coordinates.\n\n"
                "   - **reference APIs**:\n"
                "       - esv-bible-lookup: Allows for accessing specific references and data related to biblical texts, which can aid in verifying the historical context and accuracy of the locations.\n"
                "       - wikipedia: The API provides access to a broad database that may include historical details about ancient cities, supporting the validation of their locations.\n\n"
                "4. **Select the Most Suitable APIs**:\n"
                "   - google-maps: Known for its robust and precise mapping capabilities making it ideal for accurately plotting and displaying ancient biblical locations.\n"
                "   - esv-bible-lookup: Directly relates to biblical references which is necessary for validating the historical context of the mapped locations.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['mapping', 'reference']\n"
                "   - Recommend All matched APIs in 3.: ['google-maps', 'google-geocoding', 'esv-bible-lookup', 'wikipedia']\n"
                "   - Final recommended APIs: ['google-maps', 'esv-bible-lookup']\n"
    },
    {   #2つ目
        "role": "user",
        "content":"Requirements: WishGenies lets you ask for gift recommendations for those on your shopping list. You'll get great ideas because WishGenies asks people who like the same things as your recipient.\n"
                "Answer:\n"
                "1. **Identify Core Features**:\n"
                "   - Gift Recommendations: The primary feature is offering curated gift ideas based on recipient preferences.\n"
                "   - Social Preference Sharing: WishGenies leverages social data to match preferences of similar users.\n\n"
                "2. **Identify Relevant API Categories**:\n"
                "   - social: This category is relevant because WishGenies uses social preference data to obtain recommendations, potentially incorporating user profiles and interests.\n"
                "   - ecommerce: This category is relevant because the service deals with gifts, shopping lists, and potentially integrates with ecommerce platforms for product information and transactions.\n\n"
                "3. **Match APIs from Relevant Categories**:\n"
                "   - **social APIs**:\n"
                "       - facebook: Allows accessing social connections and interests that can help tailor gift recommendations based on friends' liked pages, interests, and activities.\n"
                "       - google-plus: Offers access to social data, providing a lesser option for user interaction insights compared to Facebook.\n"
                "       - topsy: Focuses on Twitter data conversations, which is useful for current preferences and social trend analysis.\n\n"
                "   - **ecommerce APIs**:\n"
                "       - bolcom-open: Offers access to product data from an online marketplace, suitable for providing gift options.\n"
                "       - shopify-admin: Integrates ecommerce functionalities that could support managing product data and transactions.\n"
                "       - amazon-product-advertising: Allows access to Amazon's extensive product catalog, ideal for sourcing gift ideas.\n"
                "       - shoppingcom: Offers product catalogs and merchant offers, useful for price comparisons and product availability.\n\n"
                "4. **Select the Most Suitable APIs**:\n"
                "   - facebook: The most suitable due to its wide array of personal interest data, ability to access friend connections, and insights into user behavior which are crucial for making relevant gift recommendations.\n"
                "   - amazon-product-advertising: As one of the largest online marketplaces with a comprehensive product catalog, it is optimal for accessing varied gift options and purchasing links.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['social', 'ecommerce']\n"
                "   - Recommend All matched APIs in 3.: ['facebook', 'google-plus', 'topsy', 'bolcom-open', 'shopify-admin', 'amazon-product-advertising', 'shoppingcom']\n"
                "   - Final recommended APIs: ['facebook', 'amazon-Product-advertising']\n"
    
    },
    {   #3つ目
    "role": "user",
    "content":"Requirements: RADAAR is a powerful social media management and collaboration platform designed for handling multiple brands. It helps marketers at every step, from scheduling and publishing posts on their profiles to analyzing their efforts. Whether you're a small business focusing on a few social media networks, an agency managing multiple brands, or an enterprise company that needs it all, RADAAR will help you drastically streamline your workflows, simplify your social media management, and save time. RADAAR provides a variety of features including tools for publishing, social media inbox, social media monitoring, and analytics.\n"
                "Answer:\n"
                "1. **Identify Core Features**:\n"
                "   - Social Media Scheduling: Supports scheduling and publishing posts, which is a critical component of social media management.\n"
                "   - Analytics and Monitoring: Provides tools for analyzing social media efforts and monitoring interactions, crucial for performance tracking.\n"
                "   - Social Media Collaboration: Enables managing multiple brands, implying the need for collaboration features.\n"
                "   - Content Management: Involves handling media like photos and videos across different social platforms.\n\n"
                "2. **Identify Relevant API Categories**:\n"
                "   - social: Essential for interacting with major social media platforms, managing posts, and analyzing engagement.\n"
                "   - photos: Important for handling image content shared on social media platforms.\n"
                "   - video: Vital for managing and sharing video content across social media channels.\n\n"
                "3. **Match APIs from Relevant Categories**:\n"
                "   - **social APIs**:\n"
                "       - twitter: Integrates with Twitter for posting, analyzing tweets, and engagement.\n"
                "       - instagram-graph: Provides access to Instagram's photo and social media functionalities.\n"
                "       - facebook:Allows accessing social connections and interests that can help tailor gift recommendations based on friends' liked pages, interests, and activities.\n"
                "       - linkedIn: Facilitates managing professional social interactions.\n"
                "       - foursquare: Offers location-based social interaction data.\n\n"
                "   - **photos APIs**:\n"
                "       - imgur: Supports sharing photos and is suitable for managing image-based content.\n"
                "       - snipshot: Allows online image editing, useful for quick modifications before posting.\n"
                "       - flickr: Access to extensive photo libraries for sharing and posting.\n\n"
                "   - **video APIs**:\n"
                "       - youtube: Essential for managing video content and integrating with YouTube's platform.\n"
                "       - vimeo: Offers tools for video processing and distribution.\n"
                "       - brightcove: Supports hosting and managing video content, suitable for enterprises.\n\n"
                "4. **Select the Most Suitable APIs**:\n"
                "   - twitter: Key for integrating with a major social media platform.\n"
                "   - instagram-graph: Crucial for managing Instagram's photo sharing capabilities.\n"
                "   - facebook:Allows accessing social connections and interests that can help tailor gift recommendations based on friends' liked pages, interests, and activities.\n"
                "   - linkedIn: Important for handling professional networking functionalities.\n"
                "   - youtube: Ideal for video content management on YouTube.\n"
                "   - vimeo: Useful for video hosting and sharing for enterprises.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['social', 'photos', 'video']\n"
                "   - Recommend All matched APIs in 3.: ['twitter', 'instagram-graph', 'facebook', 'linkedin', 'foursquare', 'imgur', 'snipshot', 'flickr', 'youtube', 'vimeo', 'brightcove']\n"
                "   - Final recommended APIs: ['twitter', 'instagram-graph', 'facebook', 'linkedin', 'youtube', 'vimeo']\n"

    },
    {   #4つ目
    "role": "user",
    "content":"Requirements: Bing Search in 2 separate languages. 2lingual Bing Search is a dual-language search tool that performs both a Bing Search and a Cross-language Bing Search. It also provides a query translation option that can be activated or deactivated for Cross-language Bing Searches. The top-ranking Bing Search Results from 2 user-selected search languages are displayed in side-by-side columns. Other features include Search Suggestions, Spelling Corrections, Cached Pages and Related Search Links.\n"
                "Answer:\n"
                "1. **Identify Core Features**:\n"
                "   - Dual-language Search: The service needs to perform searches in two languages.\n"
                "   - Cross-language Search: Queries should allow searches in multiple languages and translations.\n"
                "   - Query Translation: The option to translate queries during searches.\n"
                "   - Search Features: The inclusion of features like Search Suggestions, Spelling Corrections, and Related Search Links.\n"
                "   - Display Results: Display top results side-by-side in columns for different languages.\n\n"
                "2. **Identify Relevant API Categories**:\n"
                "   - search: Required for performing basic and cross-language search operations.\n"
                "   - translation: Necessary for translating queries and results into different languages.\n"
                "   - tools: Useful for implementing additional functionalities like search suggestions and spelling corrections.\n\n"
                "3. **Match APIs from Relevant Categories**:\n"
                "   - **search APIs**:\n"
                "       - microsoft-bing: Provides search capabilities and offers rich data APIs.\n"
                "       - bing: Provides search similar to Bing.com offering search results, and various extra data like images and more.\n\n"
                "   - **translation APIs**:\n"
                "       - microsoft-translator: A cloud-based machine translation API for translating terms and query data.\n\n"
                "   - **tools APIs**:\n"
                "       - bing-translator: A Microsoft translation service useful for translating queries and results in applications.\n\n"
                "4. **Select the Most Suitable APIs**:\n"
                "   - microsoft-bing: Offers comprehensive search features along with suggestions, corrections, and related links.\n"
                "   - bing: Known for search reliability and integration capabilities.\n"
                "   - microsoft-translator: Allows straightforward integration for translating search queries and results, aligning with dual-language operation.\n"
                "   - bing-translator: Complements the search features with translation capabilities.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['search', 'translation', 'tools']\n"
                "   - Recommend All matched APIs in 3.: ['microsoft-bing', bing, 'microsoft-translator', 'bing-translator']\n"
                "   - Final recommended APIs: ['microsoft-bing', 'bing', 'microsoft-translator', 'bing-translator']\n"
    },
    {   #5つ目
    "role": "user",
    "content":"Requirements: A new method of communication involving VOIP/wireless and cable call management phone booth systems. AirCellCall's technical architecture system combines several communication methods into one device that you can use to communicate even if you do not have a cell phone available. Designed to serve the general public, corporate and government entities.\n"
                "Answer:\n"
                "1. **Identify Core Features**:\n"
                "   - **VOIP/Wireless Communication**: The service involves VOIP, which is a core feature for handling voice and telephony services.\n"
                "   - **Call Management**: Requires managing calls, indicating the need for telephony solutions.\n"
                "   - **SMS and Messaging**: Integration for communication might involve SMS and other messaging services.\n"
                "   - **Interoperability Across Devices**: Integration of various communication methods for use without a cell phone suggests the need for versatile messaging and telephony APIs.\n"
                "   - **User Engagement for Public and Corporate Use**: Requires APIs that can scale and offer diverse functionalities for a wide user base, including corporations.\n\n"
                "2. **Identify Relevant API Categories**:\n"
                "   - telephony: Because of VOIP and call management functionalities.\n"
                "   - messaging: For handling SMS and other forms of messaging as part of communication.\n\n"
                "3. **Match APIs from Relevant Categories**:\n"
                "   - **telephony APIs**:\n"
                "       - twilio: Offers a cloud API for voice and SMS communications, catering directly to VOIP needs, scalable and reliable for a wide user base.\n"
                "       - plum-fuse: Provides IVR, outbound calling, and other telephony features suitable for call management.\n"
                "       - myvox: Voice-enable applications, good for handling calls.\n"
                "       - opencnam: Provides access to Caller ID information, complementary to call management.\n"
                "       - kookoo: API for voice and SMS suitable for building telephony apps.\n\n"
                "   - **messaging APIs**:\n"
                "       - twilio-sms: Specifically handles SMS, matches the requirement for SMS messaging support.\n"
                "       - vonage-nexmo-sms: Another API for sending and receiving SMS messages.\n"
                "       - postalmethods: Deals with messaging services through the postal gateway.\n"
                "       - amazon-sns: Provides messaging services including SMS via notifications.\n\n"
                "4. **Select the Most Suitable APIs**:\n"
                "   - twilio: Covers both voice (telephony) and SMS (messaging), making it versatile and well-suited for integrated communication services.\n"
                "   - twilio-sms: Specialized for SMS, directly supports messaging needs aligned with the service requirements.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['telephony', 'messaging']\n"
                "   - Recommend All matched APIs in 3.: ['twilio', 'plum-fuse', 'myvox', 'opencnam', 'kookoo', 'twilio-sms', 'vonage-nexmo-sms', 'postalmethods', 'amazon-sns']\n"
                "   - Final recommended APIs: ['twilio', 'twilio-sms']\n"

    }
]




few_shot_examples_detail = [
    {   #1つ目
    "role": "user",
    "content":"Requirements: Mashup showing locations of 200 places mentioned in the Bible. Going for accuracy they try to pinpoint the locations of the ruins of ancient cities instead of using the locations of modern cities with ancient names.\n"
                "Answer:\n"
                "1. **Expanding Requirements**:\n"
                "   - The mashup service's goal is to create an accurate informational display of 200 locations based on places mentioned in the Bible, emphasizing historical and archaeological accuracy rather than modern city parallels. This involves mapping features to correctly locate ancient ruins or sites and a reference system to authenticate these locations according to their biblical context.\n\n"
                "2. **Identify Core Features**:\n"
                "   - Mapping Functionality: To pinpoint the geographical locations of ancient ruins and accurately represent them on a map.\n"
                "   - Reference Data: To accurately cross-reference and retrieve data related to biblical places for validation and information accuracy.\n\n"
                "3. **Identify Relevant API Categories**:\n"
                "   - mapping: Essential to provide services like geolocation, mapping, and spatial data needed for accurately plotting ancient biblical sites.\n"
                "   - reference: Necessary to link historical and archaeological data with biblical texts for accurate identification and verification of the locations.\n\n"
                "4. **Match APIs from Relevant Categories**:\n"
                "   - **mapping APIs**:\n"
                "       - google-maps: A powerful tool for mapping and geolocation that supports detailed geospatial data visualization and location pinpointing.\n"
                "       - bing-maps: Provides comprehensive mapping facilities and geolocation services which can support the mashup's requirement for precise location mapping.\n"
                "       - mapquest: Offers mapping and geolocation services that could also be considered for alternatives.\n"
                "       - openstreetmap: A useful resource for detailed and freely-accessible mapping data.\n\n"
                "   - **reference APIs**:\n"
                "       - esv-bible-lookup: Directly supports fetching biblical texts and their correlations, vital for referencing and validating biblical locations.\n"
                "       - dbpedia: Can be used for structured data extraction related to biblical sites.\n"
                "       - wolfram-alpha: Offers computational knowledge that might support historical and biblical reference data needs.\n"
                "       - wikipedia: Provides access to a comprehensive range of historical data including references to biblical sites.\n\n"
                "5. **Select the Most Suitable APIs**:\n"
                "   - google-maps: Chosen for its superior mapping capabilities, up-to-date data, and robust API support for integrating maps with pinpoint accuracy.\n"
                "   - esv-bible-lookup: Chosen for its direct support for fetching textual and contextual biblical references, essential for validating and referencing biblical locations.\n\n"
                "### Conclusion:\n"
                "   - Recommended categories from 3.: ['mapping', 'reference']\n"
                "   - Recommended All matched APIs in 4.: ['google-maps', 'bing-maps', 'mapquest', 'openstreetmap', 'esv-bible-lookup', 'openstreetmap', 'wolfram-alpha', 'wikipedia']\n"
                "   - Final recommended APIs: ['google-maps', 'esv-bible-lookup']\n"
    },
    {   #2つ目
    "role": "user",
    "content":"Requirements: WishGenies lets you ask for gift recommendations for those on your shopping list. You'll get great ideas because WishGenies asks people who like the same things as your recipient.\n"
                "Answer:\n"
                "1. **Expanding Requirements**:\n"
                "   - WishGenies is a unique mashup service designed to provide personalized gift recommendations for users' shopping lists. This service leverages preference data from individuals who share common interests with the gift recipients, enhancing the relevance and appeal of the suggestions. The goal of WishGenies is to simplify the gift selection process by offering curated, high-quality gift ideas that align with the recipient's tastes. Core functionalities include user profile management for capturing and analyzing recipient preferences, integration with e-commerce platforms to access vast product catalogs, and social network data mining to identify users with similar interest profiles.\n\n"
                "2. **Identify Core Features**:\n"
                "   - **user Profile Management**: Critical for storing and processing recipient preferences to offer tailored gift suggestions.\n"
                "   - **ecommerce Integration**: Necessary for accessing and displaying a wide range of products.\n"
                "   - **social Network Data Integration**: Important for identifying and leveraging interest data from users with similar preferences.\n\n"
                "3. **Identify Relevant API Categories**:\n"
                "   - social: To access data from users with similar interests for personalized recommendations.\n"
                "   - ecommerce: To retrieve and present product information for the gift recommendations.\n\n"
                "4. **Match APIs from Relevant Categories**:\n"
                "   - **social APIs**:\n"
                "       - facebook-graph: Provides access to data from Facebook's social network, crucial for identifying users with similar interests.\n"
                "       - linkedin: Offers access to social data but may not directly cater to personal interests as required.\n\n"
                "   - **ecommerce APIs**:\n"
                "       - amazon-product-advertising: Comprehensive access to Amazon's vast product catalog, essential for sourcing and displaying potential gifts.\n"
                "       - woocommerce: Good for e-commerce integration, but may not offer the same breadth of products as Amazon.\n"
                "       - shopify-admin: Offers product data but may require more integration effort compared to Amazon for a wider audience reach.\n\n"
                "5. **Select the Most Suitable APIs**:\n"
                "   - facebook-graph: Best suited for accessing social graph data to connect users with similar gifting preferences.\n"
                "   - amazon-product-advertising: Ideal due to the extensive range of products and established integration capabilities.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 3.: ['social', 'ecommerce']\n"
                "   - Recommend All matched APIs in 4.: ['facebook-graph','linkedin', 'amazon-product-advertising', 'woocommerce', 'shopify-admim']\n"
                "   - Final recommended APIs: ['facebook-graph', 'amazon-product-advertising']\n"
    },
    {   #3つ目
    "role": "user",
    "content":"Requirements: RADAAR is a powerful social media management and collaboration platform designed for handling multiple brands. It helps marketers at every step, from scheduling and publishing posts on their profiles to analyzing their efforts. Whether you're a small business focusing on a few social media networks, an agency managing multiple brands, or an enterprise company that needs it all, RADAAR will help you drastically streamline your workflows, simplify your social media management, and save time. RADAAR provides a variety of features including tools for publishing, social media inbox, social media monitoring, and analytics.\n"
                "Answer:\n"
                "1. **Expanding Requirements**:\n"
                "   - RADAAR is a social media management platform aimed at multiple brands, streamlining workflows, and offering tools for post-scheduling, publishing, social inbox management, monitoring, and analytics. The goal is to simplify social media management for businesses of all sizes and provide comprehensive analytics and monitoring capabilities.\n\n"
                "2. **Identify Core Features**:\n"
                "   - **Social Media Interaction**: To manage multiple social media accounts and brands, interact with platforms such as Facebook, Instagram, Twitter, and LinkedIn.\n"
                "   - **Content Publishing**: Scheduling and publishing capabilities for posts across multiple channels.\n"
                "   - **Analytics and Monitoring**: Tools for monitoring brand mentions, analyzing performance, and gaining insights from social media analytics.\n"
                "   - **Multimedia Handling**: Support for handling photos and videos within the social media context as part of publishing and engagement.\n\n"
                "3. **Identify Relevant API Categories**:\n"
                "   - social: Interfaces with platforms like Facebook, Instagram, Twitter, and LinkedIn are crucial for social media management.\n"
                "   - photos: Required for handling photo-related content on platforms like Instagram.\n"
                "   - video: Essential for managing video content on platforms like YouTube and Vimeo. These platforms are also a part of the social media engagement and content strategies.\n\n"
                "4. **Match APIs from Relevant Categories**:\n"
                "   - **social APIs**:\n"
                "       - twitter: Allows interaction with Twitter data and services, useful for managing postings and analytics.\n"
                "       - facebook: Provides integration with Facebook social graph for posting, monitoring, and analytics.\n"
                "       - linkedin: Essential for managing professional social content.\n\n"
                "   - **photos APIs**:\n"
                "       - instagram-graph: Manages photo content specific to Instagram, blending photo management with social capabilities.\n"
                "       - flickr: While not initially listed as a goal, it is relevant for extended photo content handling but not necessarily essential.\n\n"
                "   - **video APIs**:\n"
                "       - youtube: Supports YouTube video management for content uploading and engagement.\n"
                "       - vimeo: Similar to YouTube but catering to a different audience and purpose in video content provision.\n\n"
                "5. **Select the Most Suitable APIs**:\n"
                "   - twitter: Integral for comprehensive social media management on this major network.\n"
                "   - instagram-graph**: Provides both social and photo management features essential for RADAAR.\n"
                "   - facebook: Critical for handling Facebook-specific content, social activity, and monitoring.\n"
                "   - linkedin: Needed for professional network management.\n"
                "   - youTube: Necessary for integration and video content management.\n"
                "   - vimeo: Also necessary for hosting and managing video content alongside YouTube.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 3.: ['social', 'photos', 'video']\n"
                "   - Recommend All matched APIs in 4.: ['twitter', facebook', 'linkedin', 'instagram-graph', 'flickr', 'youtube', 'vimeo']\n"
                "   - Final recommended APIs: ['twitter', 'instagram-graph', 'facebook', 'linkedin', 'youtube', 'vimeo']\n"

    },
    {   #4つ目
    "role": "user",
    "content":"Requirements: Bing Search in 2 separate languages. 2lingual Bing Search is a dual-language search tool that performs both a Bing Search and a Cross-language Bing Search. It also provides a query translation option that can be activated or deactivated for Cross-language Bing Searches. The top-ranking Bing Search Results from 2 user-selected search languages are displayed in side-by-side columns. Other features include Search Suggestions, Spelling Corrections, Cached Pages and Related Search Links.\n"
                "Answer:\n"
                "1. **Expanding Requirements**:\n"
                "   - The mashup service will be called \"2lingual Bing Search,\" which offers dual-language search capabilities by performing both a Bing Search and a Cross-language Bing Search. Users can enable or disable a translation feature for cross-language searches, ensuring that results from two chosen languages are presented side by side. Additional expected functionalities will include Search Suggestions, Spelling Corrections, Cached Pages, and Related Search Links. This will provide users with a comprehensive tool for multilingual search queries, enhancing user experience by presenting streamlined search results in multiple languages.\n\n"
                "2. **Identify Core Features**:\n"
                "   - **Multilingual Search**: Required to perform searches in two different languages at the same time.\n"
                "   - **Cross-Language Search**: Important to handle queries in one language and retrieve results in another.\n"
                "   - **Query Translation**: Necessary for the cross-language part to translate queries from one language to another.\n"
                "   - **Search Suggestions**: Helps users with query formulation by providing suggestions.\n"
                "   - **Spelling Corrections**: Ensures accuracy in search results by correcting any typos.\n"
                "   - **Cached Pages**: Allows access to cached versions of web pages.\n"
                "   - **Related Search Links**: Provides links to related searches for expanded results.\n\n"
                "3. **Identify Relevant API Categories**:\n"
                "   - search: To facilitate web searches in various languages and formats.\n"
                "   - translation: Required to translate queries between different languages.\n"
                "   - tools: To manage and enhance the presentation and handling of search data.\n\n"
                "4. **Match APIs from Relevant Categories**:\n"
                "   - search APIs**:\n"
                "       - bing: Capable of handling regular and advanced search operations including suggestions.\n"
                "       - microsoft-bing: Provides powerful search capabilities similar to Bing API.\n\n"
                "   - translation APIs:\n"
                "       - microsoft-translator: Provides a robust suite of translation services for handling multiple languages.\n\n"
                "   - tools APIs:\n"
                "       - datadog: Offers data management utilities that could assist with translation and search data organization.\n"
                "       - zapier: Enables the integration and automation of tools for optimized workflow.\n\n"
                "       - bing-translator: Offers translation capabilities needed for cross-language search.\n"
                "5. **Select the Most Suitable APIs**:\n"
                "   - bing: Directly fits the need for a traditional web search service within two languages.\n"
                "   - microsoft-bing: Ensures comprehensive search capability and complements Bing.\n"
                "   - bing-translator: Enables cross-language query translation and supports multilingual interactions.\n"
                "   - microsoft-translator: Provides enhanced translation services necessary for cross-language operations.\n\n"
                "### Conclusion:\n"
                "   - Recommended categories from 3.: ['search', 'translation', 'tools']\n"
                "   - Recommended All matched APIs in 4.: ['bing', 'microsoft-bing', 'bing-translator', 'microsoft-translator', 'datadog', 'zapier']\n"
                "   - Final recommended APIs: ['bing', 'microsoft-bing', 'bing-translator', 'microsoft-translator']\n"
    },
    {   #5つ目
    "role": "user",
    "content":"Requirements: A new method of communication involving VOIP/wireless and cable call management phone booth systems. AirCellCall's technical architecture system combines several communication methods into one device that you can use to communicate even if you do not have a cell phone available. Designed to serve the general public, corporate and government entities.\n"
                "Answer:\n"
                "1. **Expanding Requirements**:\n"
                "   - The mashup service aims to provide a comprehensive communication platform leveraging VOIP/wireless and cable call management systems. The goal is to facilitate communication without needing a personal cell phone, targeting the general public, corporates, and government entities. It should integrate multiple communication methods to operate as an advanced phone booth system, enabling calls and messages to be sent wirelessly and through cable networks.\n\n"
                "2. **Identify Core Features**:\n"
                "   - VOIP Integration: The service must support voice calling over the internet, minimizing the need for traditional phone lines.\n"
                "   - Messaging Capabilities: To allow for sending and receiving text messages as a form of communication.\n"
                "   - Call Management: Features for managing incoming and outgoing calls efficiently, possibly including call queuing and IVR systems.\n\n"
                "3. **Identify Relevant API Categories**:\n"
                "   - telephony: To support VOIP calling and integrate voice applications.\n"
                "   - messaging: Required for SMS and other messaging capabilities to complement VOIP.\n\n"
                "4. **Match APIs from Relevant Categories**:\n"
                "   - **telephony APIs**:\n"
                "       - twilio: Offers a robust telephony infrastructure for VOIP and advanced voice communications, widely used for such applications.\n"
                "       - plum-fuse: Provides cloud-based telephony services including IVR and call routing, suitable for a phone booth system.\n"
                "       - opencnam: Useful for accessing caller ID information, could enhance call management features.\n\n"
                "   - **messaging APIs**:\n"
                "       - twilio-sms: Specially designed for integrating SMS capabilities, supports sending and receiving messages.\n"
                "       - postalmethods: Offers services for sending physical mail, which can be useful for message delivery in varied formats.\n"
                "       - vonage-nexmo-sms: Provides global SMS sending capabilities, useful for a broad audience reach.\n\n"
                "5. **Select the Most Suitable APIs**:\n"
                "   - twilio: Select for its comprehensive cloud telephony services, which encompass VOIP and messaging, aligning with both telephony and messaging needs.\n"
                "   - twilio-sms: Specifically tailored for SMS integration, perfectly meeting the messaging feature requirement.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 3.: ['telephony', 'messaging']\n"
                "   - Recommend All matched APIs in 4.: ['twilio', 'plum-fuse', 'opencnam', 'twilio-sms', 'postalmethods', 'vonage-nexmo-sms']\n"
                "   - Final recommended APIs: ['twilio', 'twilio-sms']\n"

    }
]

few_shot_examples_new = [
    {
    "role": "user",
    "content":"Requirements: Breakout is the first-ever modern Workflow Management Software that automates step-by-step recurring business processes. \n"
                "Answer:\n"
                "1. **Identify Core Features**:\n"
                "   - Automation of Business Processes: Workflow management systems require integration with tools that allow automation of repetitive tasks like managing documents, communication, etc.\n"
                "   - Collaboration and Communication Tools: Integrating messaging and collaboration tools to ensure seamless communication among team members.\n"
                "   - Data Handling and Documentation: Access to data sources like email, storage solutions for document sharing, and spreadsheet capabilities for data organization is crucial.\n\n"
                "2. **Identify Relevant API Categories:\n"
                "   - Email: To integrate with email services for sending, receiving, and managing emails within workflows.\n"
                "   - Spreadsheets: For automating data entry, analysis, and sharing spreadsheets within the workflow management platform.\n"
                "   - Storage: To store and retrieve documents, files, and other data used in workflows.\n"
                "   - Tools: General purpose tools category that includes collaborative and utility applications needed for enhanced workflow management.\n\n"
                "3. **Match APIs from Relevant Categories**:\n"
                "   - **Email APIs**:\n"
                "       - mailchimp: Provides capabilities for managing email campaigns.\n"
                "       - mandrill: Offers email sending capabilities.\n"
                "       - sendGrid: Cloud-based email service with tracking and analytics.\n"
                "       - gmail: Allows access to Gmail mailboxes and can perform CRUD operations on emails.\n"
                "       - mailjet: Facilitates creating and sending emails through APIs.\n\n"
                "   - **Spreadsheets APIs**:\n"
                "       - google-sheets: Allows for extensive manipulation of spreadsheet data.\n\n"
                "   - **Storage APIs**:\n"
                "       - google-drive: A widely used cloud storage solution that allows file management.\n"
                "       - dropbox: File storage service allowing read/write file access.\n"
                "       - amazon-S3: Cloud storage service with web-service interface.\n\n"
                "   - **Tools APIs**:\n"
                "       - slack-web: Collaboration hub where information and files can be exchanged.\n"
                "       - zapier: Integration tool connecting multiple services.\n"
                "       - github: For managing source code and collaborative coding with other developers.\n\n"
                "4. **Select the Most Suitable APIs**:\n"
                "   - gmail: Chosen due to its capability to manage email as part of a workflow application.\n"
                "   - google-sheets: Allows workflows to incorporate spreadsheet data and operations, ideal for business data handling.\n"
                "   - google-drive: Essential for integrating document storage and sharing capabilities into workflows.\n"
                "   - slack-web: Integrates team collaboration features, fostering communication essential for workflow management.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['email', 'spreadsheets', 'storage', 'tools']\n"
                "   - Recommend All matched APIs in 3.: ['gmail', 'google-Sheets', 'google-Drive', 'slack-Web']\n"
                "   - Final recommended APIs: ['gmail', 'google-Sheets', 'google-Drive', 'slack-Web']\n"
    },
    {
    "role": "user",
    "content":"Requirements: EspoCRM is an open-source web application designed to build loyal relationships with customers and boost your sales. The software creates a unified collaborative place for your employees with all the necessary data inside - customer profiles and communications with them, information about opportunities, sales orders, invoices &amp; quotes. It allows to streamline the sales processes, automate routine operations, create personalized marketing campaigns and provide top quality customer service.\n"
                "Answer: \n"
                "1. **Identify Core Features**:\n"
                "   - CRM Automation: The service requirements describe automating sales processes and routine operations, which are typical for a CRM system.\n"
                "   - Communication Integration: Managing customer profiles and communications, including sales orders, implies the necessity for integrating with email and telephony systems.\n"
                "   - Data Synchronization: Handling customer data, opportunities, and service quality suggests integration with calendar systems to plan and log activities.\n"
                "   - Geo-Location Awareness: Developing better marketing campaigns and customer service may require mapping APIs to understand geographical customer distribution.\n\n"
                "2. **Identify Relevant API Categories**:\n"
                "   - mapping: For geolocation and address visualization on maps.\n"
                "   - calendars: To manage and synchronize real-time schedules related to customer and employee activities.\n"
                "   - email: For communication, managing customer correspondences, and integrating marketing campaigns.\n"
                "   - telephony: For voice communication needs with customers.\n"
                "   - other: Integration with other systems to enhance data exchange and access.\n\n"
                "3. **Match APIs from Relevant Categories**:\n"
                "   - **Mapping APIs**:\n"
                "       - google-maps: Provides comprehensive mapping and geolocation services.\n"
                "       - geoloqi: Location-based services for user management.\n"
                "       - mapquest: Basic mapping and geocoding services.\n"
                "       - bing-maps: More mapping options.\n\n"
                "   - **Calendar APIs**:\n"
                "       - google-calendar: Standard in calendar management and integration.\n"
                "       - liveconnect: For integration with Windows Live calendars.\n\n"
                "   - **Email APIs**:\n"
                "       - mailchimp: Email marketing service, useful for campaigns.\n"
                "       - sendgrid: For sending emails, including campaigns, providing analytics.\n"
                "       - gmail: Google's email management services.\n\n"
                "   - **Telephony APIs**:\n"
                "       - twilio: Well-known service for handling voice and messaging.\n"
                "       - telapi: Enable voice and SMS functionalities.\n\n"
                "   - **Other APIs**:\n"
                "       - google-contacts: Manage and synchronize contact information across platforms.\n"
                "       - bookmooch: Additional resource from the 'other' category, not strictly necessary.\n\n"
                "4. **Select the Most Suitable APIs**:\n"
                "   - google-maps: Ideal for providing geolocation and mapping services integrated with CRM.\n"
                "   - google-calendar: For integrating scheduling functionalities seamlessly.\n"
                "   - google-contacts: For managing contact information, essential in a CRM system.\n"
                "   - mailchimp: For conducting robust email marketing campaigns.\n"
                "   - twilio: Comprehensive telephony solution to manage voice and text communications.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['mapping', 'calendars', 'email', 'telephony', 'other']\n"
                "   - Recommend All matched APIs in 3.: ['google-maps', 'google-calendar', 'google-contacts', 'mailchimp', 'twilio']\n"
                "   - Final recommended APIs: ['google-maps', 'google-calendar', 'google-contacts', 'mailchimp', 'twilio']\n"
    },
    {
    "role": "user",
    "content":"Requirements: RADAAR is a powerful social media management and collaboration platform designed for handling multiple brands. It helps marketers at every step, from scheduling and publishing posts on their profiles to analyzing their efforts. Whether you're a small business focusing on a few social media networks, an agency managing multiple brands, or an enterprise company that needs it all, RADAAR will help you drastically streamline your workflows, simplify your social media management, and save time. RADAAR provides a variety of features including tools for publishing, social media inbox, social media monitoring, and analytics.\n"
                "Answer: \n"
                "1. **Identify Core Features**:\n"
                "   - Scheduling and Publishing on Social Media: RADAAR helps manage social media posts for multiple brands.\n"
                "   - Social Media Inbox and Monitoring: Essential for interacting and monitoring various social media platforms.\n"
                "   - Analytics: To analyze the effectiveness of social media campaigns.\n\n"
                "2. **Identify Relevant API Categories**:\n"
                "   - social: To manage social media interactions, scheduling, and content posting across platforms like Twitter, Facebook, LinkedIn, etc.\n"
                "   - photos: For applications like Instagram that are photo-focused and part of the social media ecosystem.\n"
                "   - video: For handling video content on platforms like YouTube and Vimeo.\n\n"
                "3. **Match APIs from Relevant Categories**:\n"
                "   - **Social**:\n"
                "       - twitter: Offers access to social interactions and data, supports content updates.\n"
                "       - facebook-graph: Provides access to social graph data for interactions, friend data, etc.\n"
                "       - linkedin: For handling professional network updates and interactions.\n"
                "       - foursquare: Location-based social media data.\n"
                "       - instagram-graph: Access to photo-sharing social platform.\n"
                "       - fullContact-person: Social data aggregation and insights.\n"
                "       - pinterest-domain: Access to pinned content, useful for scheduling to Pinterest.\n\n"
                "   - **Photos**:\n"
                "       - instagram-graph: For managing photo content on a popular social media platform.\n"
                "       - imgur: For photo sharing and uploading purposes.\n"
                "       - instagram-real-time: Real-time updates for photo content.\n"
                "       - snipshot: For photo editing capabilities.\n"
                "       - google-street-view-image: For integrating street view images.\n"
                "       - moo: For integrating photo printing capabilities.\n\n"
                "   - **Video**:\n"
                "       - youtube: Provides support for video management and integration.\n"
                "       - vimeo: Similar to YouTube, allows video hosting and integration.\n"
                "       - dailymotion: For video content integration.\n"
                "       - thetvdbcom: For television-related video content.\n"
                "       - trailer-addict: For movie trailer content integration.\n\n"
                "4. **Select the Most Suitable APIs**:\n"
                "   - twitter: Essential for managing Twitter content and interactions.\n"
                "   - instagram-graph: Provides comprehensive tools for managing Instagram content.\n"
                "   - facebook: (assumed to mean Facebook-Graph) For handling interactions on Facebook.\n"
                "   - linkedin: Vital for managing content on a professional networking platform.\n"
                "   - youtube: Useful for video content management.\n"
                "   - vimeo: Complements YouTube for video content handling.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['social', 'photos', 'video']\n"
                "   - Recommend All matched APIs in 3.: ['twitter', 'facebook-graph', 'linkedin', 'instagram-graph', 'youtube', 'vimeo']\n"
                "   - Final recommended APIs: ['twitter', 'instagram-graph', 'facebook', 'linkedin', 'youtube', 'vimeo']\n"
    },
    {
    "role": "user",
    "content":"Requirements: Provides an overview of travel highlights around the world using interactive maps with destinations such as cities, beaches, national parks and cultural sites.\n"
                "Answer: \n"
                "1. **Identify Core Features**:\n"
                "   - Interactive Maps: The service integrates interactive maps for users to explore locations (cities, beaches, national parks, etc.).\n"
                "   - Travel Highlights: The service provides information about destinations, including cultural sites.\n"
                "   - Visual Content: Incorporates visual elements like photos to enhance presentations of travel locations.\n"
                "   - Multimedia: Utilizes video content to provide an enriched user experience.\n\n"
                "2. **Identify Relevant API Categories**:\n"
                "   - mapping: To support the integration of interactive maps.\n"
                "   - photos: To access and display high-quality images of travel destinations.\n"
                "   - video: For incorporating video content that highlights travel destinations.\n\n"
                "3. **Match APIs from Relevant Categories**:\n"
                "   - **Mapping APIs**:\n"
                "       - google-maps: Essential for interactive map integration and geolocation services.\n"
                "       - bing-maps: Alternative to Google Maps with various mapping capabilities.\n\n"
                "   - **Photos APIs**:\n"
                "       - flickr: Well-known for its extensive repository of travel and destination photos.\n"
                "       - imgur: Provides images sharing capabilities, though not specifically travel-focused.\n\n"
                "   - **Video APIs**:\n"
                "       - youtube: Provides vast video content ideal for travel presentations and includes APIs for embedding and managing video content.\n"
                "       - vimeo: Similar to YouTube, offers high-quality video content and API services.\n\n"
                "4. **Select the Most Suitable APIs**:\n"
                "   - google-maps: Renowned for its comprehensive and reliable mapping services, crucial for implementing interactive maps.\n"
                "   - flickr: Offers an extensive collection of high-quality photos, suitable for showcasing scenic travel destinations.\n"
                "   - youtube: Widely used video platform; the API allows integration of destination-specific video content that can highlight travel features effectively.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['mapping', 'photos', 'video']\n"
                "   - Recommend All matched APIs in 3.: ['google-maps', 'flickr', 'youtube', 'bing-maps', 'imgur', 'vimeo']\n"
                "   - Final recommended APIs: ['google-maps', 'flickr', 'youtube']\n"
    },
    {
    "role": "user",
    "content":"Requirements: Instantly Find and Embed Videos for all the products you sell, from all the major media websites including YouTube, Facebook and Vimeo. Display embedded media as the Product Featured Video or in a custom tab. You can automate the entire process and you have detailed control over which videos show on which products. Get Started for Free!\n"
                "Answer: \n"
                "1. **Identify Core Features**:\n"
                "   - Video retrieval: The service needs to find videos from various online media platforms such as YouTube, Facebook, and Vimeo.\n"
                "   - Video embedding: The ability to embed videos in webpages, particularly for use as a product featured video or in a custom tab.\n"
                "   - Automation and control: Automatically process and manage the association of videos to products, while allowing detailed control over video selection.\n\n"
                "2. **Identify Relevant API Categories**:\n"
                "   - video: To retrieve and embed videos from platforms like YouTube, Facebook, and Vimeo.\n"
                "   - social: Since platforms like YouTube and Facebook can be considered part of social media, APIs that connect with them fall under this category.\n\n"
                "3. **Match APIs from Relevant Categories**:\n"
                "   - **Video APIs**:\n"
                "       - youtube: Directly find and embed YouTube videos.\n"
                "       - vimeo: Access and embed videos from Vimeo.\n"
                "       - dailymotion: Provides APIs to access video content.\n"
                "       - brightcove: A platform offering online video services.\n"
                "       - stupeflix: Allows creation of videos from media elements.\n\n"
                "   - **Social APIs**:\n"
                "       - facebook-graph: For accessing and embedding videos from Facebook.\n"
                "       - linkedin: Typically not video-centric but falls under the social category.\n"
                "       - foursquare: More targeted at location data, indirectly relevant.\n"
                "       - twitter: Historically a relevant social platform.\n\n"
                "4. **Select the Most Suitable APIs**:\n"
                "   - youtube: For integrating YouTube video content.\n"
                "   - vimeo: For integrating Vimeo video content.\n"
                "   - dailymotion: Enables additional video options similar to YouTube/Vimeo.\n"
                "   - facebook: For embedding Facebook-hosted video content.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['video', 'social']\n"
                "   - Recommend All matched APIs in 3.: ['youtube', 'vimeo', 'dailymotion', 'facebook-graph', 'brightcove', 'stupeflix']\n"
                "   - Final recommended APIs: ['youtube', 'vimeo', 'dailymotion', 'facebook']\n"
    }
]

few_shot_examples_new_oic = [
    {
     "role": "user",
    "content": "requiremets: Breakout is the first-ever modern Workflow Management Software that automates step-by-step recurring business processes. \n "
                "**Reasoning**:\n"
                "To provide the requested recommendations for the modern Workflow Management Software \"Breakout,\" we must consider the specified correct categories and APIs as well as the available categories and APIs. The correct categories for \"Breakout\" are 'email', 'spreadsheets', 'storage', and 'tools.' Next, we will cross-reference the APIs in the available list to identify which belong to these categories. The APIs should also fit the related functional requirements of the Workflow Management Software, which focuses on automating business processes, communication, and task management.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['email', 'spreadsheets', 'storage', 'tools']\n"
                "   - Recommend All matched APIs in 3.: ['gmail', 'google-Sheets', 'google-Drive', 'slack-Web']\n"
                "   - Final recommended APIs: ['gmail', 'google-Sheets', 'google-Drive', 'slack-Web']\n"
    },
    {
    "role": "user",
    "content": "requiremets: EspoCRM is an open-source web application designed to build loyal relationships with customers and boost your sales. The software creates a unified collaborative place for your employees with all the necessary data inside - customer profiles and communications with them, information about opportunities, sales orders, invoices &amp; quotes. It allows to streamline the sales processes, automate routine operations, create personalized marketing campaigns and provide top quality customer service.\n"
                "Answer: \n"
                "- The requirements indicate a need for categories that serve customer relationship management (CRM) and sales functionalities, including email communication and telephony.\n"
                "- The relevant categories from the listed available APIs align with the functionalities required:\n"
                "   - 'email' for communication and marketing campaigns,\n"
                "   - 'telephony' for any voice or SMS related communications,\n"
                "   - 'calendars' for managing appointments and schedules,\n"
                "   - 'mapping' for location-based services.\n"
                "- The correct APIs include those which provide services such as CRM function integration and marketing automation.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['mapping', 'calendars', 'email', 'telephony', 'other']\n"
                "   - Recommend All matched APIs in 3.: ['google-maps', 'google-calendar', 'mailchimp', 'twilio']\n"
                "   - Final recommended APIs: ['google-maps', 'google-calendar', 'mailchimp', 'twilio']\n"
    },
    {
    "role": "user",
    "content": "requiremets: RADAAR is a powerful social media management and collaboration platform designed for handling multiple brands. It helps marketers at every step, from scheduling and publishing posts on their profiles to analyzing their efforts. Whether you're a small business focusing on a few social media networks, an agency managing multiple brands, or an enterprise company that needs it all, RADAAR will help you drastically streamline your workflows, simplify your social media management, and save time. RADAAR provides a variety of features including tools for publishing, social media inbox, social media monitoring, and analytics. \n "
                "Answer: \n"
                "- RADAAR focuses primarily on social media management, which fits into the \"social\" category.\n"
                "- It also offers analytics capabilities, pointing to features that fit well under the \"analytics\" and \"tools\" categories, but based on the requirement given, the primary focus is on social media interactions, therefore primarily categorizing it under 'social'.\n"
                "- The APIs of interest for integration based on the description of RADAAR include major social media platforms such as Twitter, Instagram (via its Graph API), Facebook, LinkedIn, YouTube, and Vimeo, which are vital for content publishing and monitoring on the platforms RADAAR manages.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories: ['social', 'photos', 'video']\n"
                "   - Recommend All matched APIs: ['twitter', 'instagram-graph', 'facebook', 'linkedin', 'youtube', 'vimeo']\n"
                "   - Final recommended APIs: ['twitter', 'instagram-graph', 'facebook', 'linkedin', 'youtube', 'vimeo']\n"
    },
    {
    "role": "user",
    "content": "requiremets: Provides an overview of travel highlights around the world using interactive maps with destinations such as cities, beaches, national parks and cultural sites.\n "
                "Answer: \n"
                "1. The requirement is to provide an overview of travel highlights around the world using interactive maps, which includes destinations such as cities, beaches, national parks, and cultural sites. This indicates a need for APIs related to mapping, media (like photos and videos), and travel.\n"
                "2. The correct categories provided by the user are \"video\", \"mapping\", and \"photos\". We need to identify the relevant categories available in the system and match them with the requirements.\n"
                "3. The correct APIs provided are \"youtube\", \"google-maps\", and \"flickr\". We need to check if these APIs are available in the currently listed APIs and if they fit inside the right categories.\n\n"
                "### Conclusion:\n"
                "   - Recommend categories from 2.: ['mapping', 'photos', 'video']\n"
                "   - Recommend All matched APIs in 3.: ['youtube', 'google-maps', 'flickr']\n"
                "   - Final recommended APIs: ['youtube', 'google-maps', 'flickr']\n"
    },
    {
    "role": "user",
    "content": "requiremets: Instantly Find and Embed Videos for all the products you sell, from all the major media websites including YouTube, Facebook and Vimeo. Display embedded media as the Product Featured Video or in a custom tab. You can automate the entire process and you have detailed control over which videos show on which products. Get Started for Free!\n "
                "Answer: \n"
                "**Reasoning**:\n"
                "Based on your requirement to instantly find and embed videos for products across major media sites including YouTube, Facebook, and Vimeo, I will identify relevant categories and APIs that match the needs for embedding and controlling video content. The key categories that align with your needs are 'video' and 'social', as these platforms provide access to video content and social interactivity.\n\n"
                "### Conclusion:\n"
                "   - Recommended categories: **['video', 'social']**\n"
                "   - Recommended All matched APIs: **['youtube', 'facebook', 'vimeo', 'dailymotion']**\n"
                "   - Final recommended APIs: **['youtube', 'facebook', 'vimeo', 'dailymotion']**\n"
    }
]
